name: 'Auto Bump Version + Create Tag'

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  bump-version-create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: 'Bump version | Major'
        if: contains(github.event.pull_request.title, '[MAJOR]')
        run: npm version major

      - name: 'Bump version | Minor'
        if: contains(github.event.pull_request.title, '[MINOR]')
        run: npm version minor

      - name: 'Bump version | Patch'
        if: contains(github.event.pull_request.title, '[MINOR]') == false && contains(github.event.pull_request.title, '[MAJOR]') == false
        run: npm version patch

      - name: Setup git
        run: |
          git config user.name 'Nazmuz Pranto'
          git config user.email 'npranto4@gmail.com'

      - name: Push latest version
        run: git push origin develop --follow-tags
