name: 'Auto Bump Version + Create Tag'

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  bump-version-create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install npm
        run: npm install
      - name: Get version bump type
        run: |
          if [[ "$(jq -r '.pull_request.title' ${{ toJson(github) }}) " == *"[MINOR]"* ]]; then
            echo "minor"
          elif [[ "$(jq -r '.pull_request.title' ${{ toJson(github) }}) " == *"[MAJOR]"* ]]; then
            echo "major"
          else
            echo "patch"
          fi
        id: version_bump_type
      - name: Bump version
        run: |
          npm version ${{ steps.version_bump_type.output }}
      - name: Setup git
        run: |
          git config user.name 'Nazmuz Pranto'
          git config user.email 'npranto4@gmail.com'
      - name: Push latest version
        run: git push origin develop --follow-tags
