name: 'Custom Branch Deploy'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to deploy'
        required: true

jobs:
  custom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # - name: Setup git
      #   run: |
      #     git config user.name 'Nazmuz Pranto'
      #     git config user.email 'npranto4@gmail.com'

      - name: Check if branch exists
        run: |
          BRANCH=${{ inputs.branch }}
          if ! git ls-remote --heads origin $BRANCH; then
            echo "Branch $BRANCH does not exist. Skipping deployment."
            exit 78
          fi

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: 'build'
          production-branch: ${{ inputs.branch }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy BRANCH: [${{ inputs.branch }}] from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: 5hUx5xphYqJbZvPuHuzNQnlKaRNYnIm926gG52uEGBU
          NETLIFY_SITE_ID: 09797208-fcaa-49da-b67f-753fca2b2a6a
        timeout-minutes: 1

      # - name: Log deployed URL
      #   run: echo "Deployed URL: https://$BRANCH.netlify.app"
