name: 'Changelog'

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
